// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IWormholeReceiver
 * @notice Interface for contracts that receive messages from Wormhole.
 * @dev Based on Wormhole documentation.
 */
interface IWormholeReceiver {
    /**
     * @notice Receive a message from Wormhole.
     * @param payload The message payload bytes.
     * @param additionalVaas An array of additional VAA bytes used for delivery.
     * @param sourceAddress The address of the sending contract on the source chain, in Wormhole bytes32 format.
     * @param sourceChain The Wormhole chain ID of the source chain.
     * @param deliveryHash A hash generated by the Wormhole Relayer (or core bridge).
     */
    function receiveWormholeMessages(
        bytes memory payload,
        bytes[] memory additionalVaas, // Renamed from empty bytes[] in prompt example
        bytes32 sourceAddress,
        uint16 sourceChain,
        bytes32 deliveryHash
    ) external payable;
}
